### PR TITLE
Updated to FSharp 5.x

### PR DESCRIPTION
**Pull request by anthony-mi**

### CODE REVIEW

**Comment by xperiandri** [comment]
@vbfox, @Zaid-Ajaj we stuck on .NET version change. There are strange issues with package resolution wth packet. .NET 5 can't resolve framework from packages that target .NET Standard 2.0 and .NET Core App 3.1
Do you have any idea what can be wrong?

**Comment by Zaid-Ajaj** [comment]
@xperiandri I don't know to be honest. Not sure if this library is maintained anymore. Are you upgrading this library for [Snowflaqe#32](https://github.com/Zaid-Ajaj/Snowflaqe/issues/32)? Because my idea was to start using Spectre.Console instead 🤔

**Comment by vbfox** [comment]
I don't really maintain it as I don't do much .Net these days

Might get some time this weekend to look at the build but ideally I'd like to not drop having a pre-net5 version available in the package if still humanely possible.

If someone has a clean PR that builds that would be cool because I have much things to catch up. For example this repo doesn't get paket from repo tools so either it should be switched to Nuget or switched to a modern way to get paket

**Comment by xperiandri** [comment]
OK, we can switch to NuGet if you authorize

**Comment by xperiandri** [comment]
We've only updated tests, the core library is still .NET Standard 2.0

**Comment by vbfox** [comment]
I updated the lib, thanks 🙇🏼

**Pull request closed without merging**
